# Generated by Django 4.0.4 on 2022-05-08 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.CharField(max_length=25)),
                ('userEmail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('userPassword', models.CharField(max_length=20)),
                ('userPhoto', models.ImageField(default='', null=True, upload_to='', verbose_name='photos/%y/%m/%d')),
                ('signedIn', models.BooleanField(default=False)),
                ('userType', models.CharField(choices=[('FR', 'Admin'), ('SO', 'User')], default='SO', max_length=2)),
                ('userCart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carts.cart')),
            ],
        ),
    ]
