# Generated by Django 4.0.4 on 2022-05-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPhoto',
            field=models.ImageField(default='media/profilePic.jpg', null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
