# Generated by Django 4.0.4 on 2022-05-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_userphoto_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('AD', 'Admin'), ('US', 'User'), ('SE', 'Seller')], default='US', max_length=2),
        ),
    ]
