# Generated by Django 4.0.4 on 2022-05-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['userFirstName'], 'verbose_name': 'NormalUsers'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='userName',
        ),
        migrations.AddField(
            model_name='user',
            name='userFirstName',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='userLastName',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
