# Generated by Django 4.0.4 on 2022-05-17 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_remove_product_productdiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartName', models.CharField(default='My Cart', max_length=30)),
                ('cartProducts', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
