# Generated by Django 4.0.4 on 2022-05-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_productdiscount'),
        ('carts', '0002_remove_cart_cartproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cartProducts',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
