# Generated by Django 4.0.4 on 2022-05-10 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_product_productactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('companyName', models.CharField(max_length=25)),
                ('taxNumber', models.CharField(max_length=25)),
                ('sellerEmail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('sellerPassword', models.CharField(max_length=20)),
                ('companyDiscription', models.TextField(default='no discription available', null=True)),
                ('sellerPhoto', models.ImageField(default='media/profilePic.jpg', null=True, upload_to='', verbose_name='photos/%y/%m/%d')),
                ('signedIn', models.BooleanField(default=False)),
                ('sellerProducts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
