# Generated by Django 4.0.4 on 2022-05-14 16:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('taxNumber', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('companyDiscription', models.TextField(default='no discription available', null=True)),
                ('sellerPhoto', models.ImageField(default='media/profilePic.jpg', null=True, upload_to='', verbose_name='photos/%y/%m/%d')),
                ('is_active', models.BooleanField(default=False)),
                ('last_login', models.DateField(default=datetime.datetime.now)),
                ('sellerProducts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('userAuth', models.ManyToManyField(null=True, to='core.authorization')),
            ],
        ),
    ]
