# Generated by Django 4.0.4 on 2022-05-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='userAuth',
        ),
        migrations.AddField(
            model_name='seller',
            name='userAuth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.authorization'),
        ),
    ]
