# Generated by Django 4.0.4 on 2022-05-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_remove_seller_userauth_seller_userauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='username',
            new_name='companyName',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='sellerProducts',
        ),
        migrations.AlterField(
            model_name='seller',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='sellerPhoto',
            field=models.ImageField(default='media/profilePic.jpg', null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
