# Generated by Django 4.0.4 on 2022-05-14 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, max_length=20, null=True)),
                ('productDiscription', models.TextField(default='no discription', null=True)),
                ('productImage', models.ImageField(default='media/productPic.jpg', null=True, upload_to='photos/%y/%m/%d')),
                ('uploadingDate', models.DateField(default=datetime.datetime.now)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('productActivation', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'products',
                'ordering': ['uploadingDate'],
            },
        ),
    ]
