# Generated by Django 4.0.4 on 2022-05-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productDiscription',
            field=models.TextField(choices=[('NONE', 'None'), ('HOMEELECTRONICS', 'Homeelectronics'), ('USER', 'Phone'), ('SELLER', 'Laptops'), ('WOMENWEAR', 'Womenwear'), ('MENWEAR', 'Menwear'), ('KIDSEWAR', 'Kidswear'), ('FURNATURE', 'Furnature'), ('GAMES', 'Games')], default='NONE'),
        ),
    ]
