# Generated by Django 4.0.4 on 2022-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productOldPrice',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
