# Generated by Django 4.0.4 on 2022-05-16 13:37

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=products.models.Product.discount, null=True),
        ),
    ]
