# Generated by Django 4.0.4 on 2022-05-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_discount_product_discountfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discountField',
            new_name='productDiscount',
        ),
    ]
