# Generated by Django 4.0.4 on 2022-05-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_discountfield_product_productdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productDiscount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
