# Generated by Django 4.0.4 on 2022-05-16 14:01

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_productdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productDiscount',
            field=models.IntegerField(default=products.models.Product.discount, null=True),
        ),
    ]
