# Generated by Django 4.0.4 on 2022-05-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_rename_username_seller_companyname_and_more'),
        ('products', '0010_remove_product_productdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productSeller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sellers.seller'),
        ),
    ]
