# Generated by Django 4.0.4 on 2022-05-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_soldstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='soldStatus',
        ),
        migrations.AddField(
            model_name='product',
            name='Available',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
