# Generated by Django 4.0.4 on 2022-05-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_soldstatus_product_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Available',
            new_name='available',
        ),
    ]
