# Generated by Django 4.0.4 on 2022-05-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_available_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(default='media/productPic.jpg', null=True, upload_to='photos/{year}/{month}/{day}'),
        ),
    ]
