# Generated by Django 4.0.4 on 2022-05-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(default='productPic.jpg', null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
