# Generated by Django 4.0.4 on 2022-06-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(default='media/productPic.jpg', null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
